### PR TITLE
(WIP) feat(postinstall): allow installation from npm registry

### PR DESCRIPTION
**Pull request by zaida04**
Allow people to download rslint through the npm registry. All that is downloaded is `postinstall.js` which is what actually gets the prebuilt binary at the release matching the package.json version and OS type.

As of this opening of the pr, right now only manually executing the bin path works (ex. `./node_modules/rslint/bin/rslint.exe`). I have this pr marked as draft as there are some problems that are needed to be fixed before it's ready to merge.

- [ ] support use of npx
- [ ] support globally installing
- [ ] add bin path in package.json (not sure how to go about this one considering the file extension might be different depending on which OS you are on)

### CODE REVIEW

**Comment by Stupremee** [comment]
I'm not sure if it's the best thing to put the package.json and others into the root of the project. We could make an extra folder `packages/npm` where we can also put other packages (like AUR, etc)

**Comment by zaida04** [comment]
At the advice of the repo owner, I put it in the root. If you think it's better I separate it still, I will go ahead and do so.
image

**Comment by RDambrosio016** [comment]
Yeah i agree with @Stupremee, i dont think we will support other managers soon but it may be helpful to cleanly separate it

**Comment by Stupremee** [comment]
@zaida04 Status Update:

We definitely want to add this feature, and if you want, you can also implement it.
But we'll most likely wait until we are ready for a 0.3.0 release, which will also contain
more CI release targets, and a determined name for all releases, so you can download them via Node for any future release.

Regarding unsupported Targets/Architectures, we just want to throw an error and say that
you have to build RSLint yourself to make it work.

I can ping you here once we want this feature. then you can fix it and we can merge

**Pull request closed without merging**
