### PR TITLE
(WIP) TypeScript support

### PR DESCRIPTION
**Pull request by RDambrosio016**
This WIP pull request adds support for TypeScript. Most of this work is simply parser work, there is little runner and lexer work to support typescript. I will be adding TS in distinct steps:

- [x] Type parsing
- [x] Expr changes
- [x] Stmt changes
- [x] Decl changes
- [x] Misc integration/parsing work
- [x] Tests

Every single runner rule should work since TypeScript support simply adds new properties to existing nodes.

### CODE REVIEW

**Comment by RDambrosio016** [comment]
One odd thing i saw when looking at swc's handling of typescript is that they try parsing a typescript component then abandon it and backtrack if its not successful, im not sure we want to do that, the parser should be able to recover no matter what. Additionally, i think id rather parse `async <T>() => {}` in a js file as you would a typescript file but then change the type param node's kind to `ERROR` and issue an error.

**Comment by Stupremee** [comment]
The last idea, do you just mean the specific example (`async <T>() => {}`) or in general, to parse every valid typescript code as javascript code, but emit `ERROR` nodes?

**Comment by RDambrosio016** [comment]
TypeScript extensions to js code, that being decorators, return types, type args, type params, etc

**Comment by RDambrosio016** [comment]
There are other things that typescript adds here and there like eval and arguments not being allowed as assignment targets in strict ts code but those will only be an error in typescript code

**Comment by Stupremee** [comment]
Have you started on the Type checker yet? I might be interested in implementing it or helping out

**Comment by RDambrosio016** [comment]
No, the type checker wont come any time soon, its a huge undertaking, and first we need to have reliable parsing. The tsc checker isnt simple either, its 40 kloc in a single file. I know the swc developer is working on one but hes chosen to make it closed source.

**Comment by Stupremee** [comment]
Oh okay. That sounds really bad

**Comment by RDambrosio016** [comment]
The type checker will be a completely separate thing months down the line, its important to have a good linter first and foremost.

**Comment by RDambrosio016** [comment]
Well the type checker has a lot of features, it can type check js code with jsdoc, it can derive types from jsdoc, it does incremental, it has control flow analysis, etc.

**Comment by RDambrosio016** [comment]
Ts parsing is posing an interesting issue, we need to backtrack to parse ts if parsing type args failed, but the parser is error tolerant so it will go on even if there are errors. This means i probably need to have state for the parser to know if it should immediately exit or try to recover, ugh

**Comment by RDambrosio016** [comment]
Update, every test from the test suite passes, im sure i will find some bugs in the wild later on but those can be easily fixed, i need to update the readme and some docs and i will finally merge this after so long 🎉

**Comment by RDambrosio016** [comment]
There are still a couple things to do like make the ts tests actually run in CI but i can do that later, ill go ahead and merge this finally

**Pull request merged**
