### PR TITLE
Fix object computed getter/setter parsing

### PR DESCRIPTION
**Pull request by jamiebuilds**
There are other places (like in decl.rs) where it just checks `p.nth(1) != T!['(']` but I think thats a little too forgiving and using that broke a _lot_ of test262 tests.

### CODE REVIEW

**Comment by jamiebuilds** [comment]
Before:
```
┌───────────┬────────┬────────┬────────┬──────────┐
│ Tests ran │ Passed │ Failed │ Panics │ Coverage │
├───────────┼────────┼────────┼────────┼──────────┤
│   17487   │ 16632  │  854   │   1    │  95.11   │
└───────────┴────────┴────────┴────────┴──────────┘
```
After:
```
┌───────────┬────────┬────────┬────────┬──────────┐
│ Tests ran │ Passed │ Failed │ Panics │ Coverage │
├───────────┼────────┼────────┼────────┼──────────┤
│   17487   │ 16666  │  820   │   1    │  95.31   │
└───────────┴────────┴────────┴────────┴──────────┘
```

**Comment by jamiebuilds** [comment]
There's also this comment in decl.rs that is confusing:

```rs
// FIXME: handle get* which is a property + a generator
```

- `({ *get() {} })` is the generator syntax for a method named "get"
- `({ get *name() {} })` is invalid syntax

Am I missing something?

**Comment by Stupremee** [comment]
> 
> 
> There's also this comment in decl.rs that is confusing:
> 
> ```rust
> // FIXME: handle get* which is a property + a generator
> ```
> 
>     * `({ *get() {} })` is the generator syntax for a method named "get"
> 
>     * `({ get *name() {} })` is invalid syntax
> 
> 
> Am I missing something?

Unfortunately, I have no idea what the comment means, as I didn't write the parser code.

Otherwise, this looks good. Thank you very much!

**Review by Stupremee — APPROVED** [review]
After the clippy lint is fixed I will merge!

**Comment by HerringtonDarkholme** [comment]
Hi, I think the lint is irrelevant to the pull request and the clippy issue  has already been solved in master. Can we merge this?

**Comment by Stupremee** [comment]
I missed that :sweat_smile: 
Thanks for the reminder

**Pull request merged**
